---
name: birthday_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.0-232.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.3
  flutter_screenutil: ^5.8.4
  url_launcher: ^6.1.12
  yandex_mapkit: ^3.3.3
  auto_size_text: ^3.0.0
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/general/
  - assets/images/general/menu/
  - assets/images/general/entertainments/
  fonts:
  - family: Jost
    fonts:
    - asset: assets/fonts/Jost-VariableFont_wght.ttf
    - asset: assets/fonts/Jost-Medium.ttf
      weight: 500
  - family: Yeseva One
    fonts:
    - asset: assets/fonts/YesevaOne-Regular.ttf
