// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBke7E0vPOzjqS9v6azAtzTNTSxdKzJNsw',
    appId: '1:898467000947:web:374b4ceb87eb32a2e67006',
    messagingSenderId: '898467000947',
    projectId: 'birthday-intern-project',
    authDomain: 'birthday-intern-project.firebaseapp.com',
    storageBucket: 'birthday-intern-project.appspot.com',
    measurementId: 'G-D2P0F7BL6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAICYKIJTJ_skDHmDM_3qtIogH60VlVmSA',
    appId: '1:898467000947:android:c29c648e08d89ceae67006',
    messagingSenderId: '898467000947',
    projectId: 'birthday-intern-project',
    storageBucket: 'birthday-intern-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyO4RSz9XT80SXXn5w17WpntXWltpB7hY',
    appId: '1:898467000947:ios:075d0808f3190f33e67006',
    messagingSenderId: '898467000947',
    projectId: 'birthday-intern-project',
    storageBucket: 'birthday-intern-project.appspot.com',
    iosClientId: '898467000947-t2hgqee1q10t6c9vr3iem7uube4r5tlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.birthdayApp',
  );
}
